### ISSUE TITLE
Image size

### ISSUE THREAD

**Issue by Bruno-Alvim-Duarte** [azu/validate-image-type#9]
It should be great if we can validate the image size too in addition to the type

**Comment by azu** [comment]
It is out of scope.

In many cases, it is the server that accepts the request that wants to limit the file size.
In that case, you can check by looking at the size of the request, not the image.
Request handlers such as [busboy](https://github.com/mscdex/busboy)/[Multer](https://github.com/expressjs/multer) already implement that functionality.
Therefore, it is not in the scope of this library, which is limited to “image”.
